import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { roboto } from "@/font";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body
       
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
